version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: postgresdb
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: groupprojectdb
      POSTGRES_USER: groupuser
      POSTGRES_PASSWORD: grouppassword
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
